@api = http://localhost:3000/quirofanos

### Obtener todos los quirófanos
GET {{api}}

### Registrar un nuevo quirófano
POST {{api}}
Content-Type: application/json

{
    "numero_quirofano": 1,
    "id_doctor": 1,
    "id_patient": 1,
    "n_enfermeros": 3
}

### Obtener un quirófano por ID
GET {{api}}/1

### Eliminar un quirófano por ID
DELETE {{api}}/1

### Obtener la cantidad total de quirófanos
GET {{api}}/count

### Actualizar un quirófano por ID
PUT {{api}}/1
Content-Type: application/json

{
    "id_doctor": 2,
    "id_patient": 2,
    "n_enfermeros": 4
}